services:
  app:
    build: .
    ports:
      - 8081:80
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - geocache-network
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - LOG_FORMAT=${LOG_FORMAT:-standard}
      - VERBOSE_LOGGING=${VERBOSE_LOGGING:-true}

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - geocache-network

networks:
  geocache-network:
    driver: bridge

volumes:
  redis-data: